trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node.js 20.x'

- script: |
    npm install -g npm@latest
    npm install
  displayName: 'Install npm packages'

- script: |
    npx tsc
  displayName: 'Compile TypeScript'

- script: |
    npx sass src/styles.scss dist/styles.css
  displayName: 'Compile SCSS to CSS'

- task: CopyFiles@2
  inputs:
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
  displayName: 'Publish Pipeline Artifact'
  