# Nom du pipeline
name: CI-CD Pipeline

# Déclencheurs du pipeline
trigger:
  branches:
    include:
      - main

# Variables du pipeline
variables:
  buildConfiguration: 'Release'

# Pool d'agents Azure DevOps
pool:
  vmImage: 'ubuntu-latest'

# Étapes du pipeline
steps:
# Étape 1 : Vérifier le code source
- checkout: self

# Étape 2 : Installer Node.js
- task: UseNode@1
  inputs:
    version: '16.x'

# Étape 3 : Installer les dépendances
- script: |
    npm install
  displayName: 'Installer les dépendances'

# Étape 4 : Construire l'application
- script: |
    npm run build
  displayName: 'collaborator_management'

# Étape 5 : Exécuter les tests
- script: |
    npm test
  displayName: 'Exécuter les tests'

# Étape 6 : Publier les artefacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'

