trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm test
  displayName: 'Install dependencies, build, and test'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: '$(dockerId)/collaborator_management_github'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'MyDockerRegistryServiceConnection'  # Assurez-vous que le nom correspond à celui créé
    tags: |
      latest
  displayName: 'Build and push Docker image'