name: CI-CD Pipeline

trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '16.x'

  - script: |
      npm install
    displayName: 'Installer les dépendances'

  - script: |
      npm run build
    displayName: 'collaborator_management'

  - script: |
      npm test
    displayName: 'Exécuter les tests'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist'
      ArtifactName: 'drop'
      publishLocation: 'Container'