name: Deploy to Azure

on:
  push:
    branches:
      - master  # Assurez-vous que la branche correspond à celle de votre dépôt

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Authentification GitHub
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Supprimer et reconfigurer `.git`
        run: |
          rm -rf .git
          git init
          git remote add origin https://github.com/USERNAME/REPO_NAME.git

      - name: Se connecter à Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Construire et pousser l'image Docker
        run: |
          docker build -t ${{ secrets.ACR_NAME }}/mon-image:latest .
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push ${{ secrets.ACR_NAME }}/mon-image:latest

      - name: Déployer sur Azure
        run: |
          az acr repository show-tags --name ${{ secrets.ACR_NAME }} --repository mon-image
